#! /bin/sh

feh --bg-scale --randomize $HOME/.config/wallpapers/*
pgrep -x sxhkd > /dev/null || sxhkd &
compton &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           0

bscp config top_padding             30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# for spiral mode, longest_side is by default
bspc config automatic_scheme spiral

# xprop | grep WM_CLASS
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a konsole desktop='^1'
bspc rule -a youtube-music-desktop-app desktop='^2'
bspc rule -a Spotify desktop='^2'
bspc rule -a Anydesk desktop='^3'
bspc rule -a Google-chrome desktop='^9'
bspc rule -a Firefox desktop='^10'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
