#! /bin/sh

feh --bg-scale --randomize $HOME/.config/wallpapers/*
pgrep -x sxhkd > /dev/null || sxhkd &
compton &

if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
  xrandr --output eDP-1 --primary --mode 1600x900 --rotate normal --output HDMI-1 --mode 1920x1080 --rotate normal --right-of eDP-1
fi

bspc monitor eDP-1 -d I II III IV V VI VII
bspc monitor HDMI-1 -d VIII IX X

bspc config focused_border_color "#252b30"
bspc config normal_border_color "#31404d"

bspc config border_width         0
bspc config window_gap           0

bscp config top_padding             30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# for spiral mode, longest_side is by default
bspc config automatic_scheme spiral

# xprop | grep WM_CLASS
bspc rule -a konsole desktop='^1'
bspc rule -a youtube-music-desktop-app desktop='^2'
bspc rule -a Spotify desktop='^2'
bspc rule -a Anydesk desktop='^3'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a jetbrains-idea-ce desktop='^8'
bspc rule -a Google-chrome desktop='^9'
bspc rule -a Firefox desktop='^10'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# bspc rule -a Firefox:Toolkit sticky=on state=floating desktop='^1'
bspc rule -a firefox:Toolkit state=floating layer=above

$HOME/.config/polybar/launch.sh
